---

workflow-dir:
    "/home/prikhi/.tasks"
archive-dir:
    "/home/prikhi/.tasks/archive"
projects-dir:
    "/home/prikhi/.tasks/projects"

sync:
    server-url: https://smos.sleepanarchy.com
    username: prikhi
