---

workflow-dir:
    "/home/prikhi/.tasks"

sync:
    server-url: https://smos.sleepanarchy.com
    username: prikhi

keys:
    file:
        entry:
            - action: forestPromoteSubTree
              key: <<
            - action: forestDemoteSubTree
              key: ">>"
        header:
            - action: forestPromoteSubTree
              key: <<
            - action: forestDemoteSubTree
              key: ">>"

scheduler:
    schedule:
        - description: "Yearly Accounting"
          template: templates/accounting-yearly.smos.template
          destination: projects/accounting/[ %Y ].smos
          schedule: "5 5 1 1 *"
        - description: "Monthly Accounting"
          template: templates/accounting.smos.template
          destination: projects/accounting/[ %Y ]-[ %m ].smos
          schedule: "15 5 1 * *"
        - description: "Taxes Accounting"
          template: templates/accounting-taxes.smos.template
          destination: projects/accounting/[ %Y ]-taxes.smos
          schedule: "15 5 31 12 *"
        - description: "Weekly Japanese"
          template: templates/japanese.smos.template
          destination: projects/japanese/[ %Y ]-W[ %W ].smos
          schedule: "0 0 * * 1"
