---

workflow-dir:
    "/home/prikhi/.tasks"

sync:
    server-url: https://smos.sleepanarchy.com
    username: prikhi

keys:
    file:
        entry:
            - action: forestPromoteSubTree
              key: <<
            - action: forestDemoteSubTree
              key: ">>"
        header:
            - action: forestPromoteSubTree
              key: <<
            - action: forestDemoteSubTree
              key: ">>"
