#!/bin/sh

# Source system config
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Xresources for urxvt
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# flashplugin
export VDPAU_NVIDIA_NO_OVERLAY=1

# Set some variables now so they are available to Awesome
export EDITOR=vim
export PATH=$PATH:~/.bin:~/.cabal/bin

# NixOS Specifics
if [ -e /etc/NIXOS ];
then
    export GTK_DATA_PREFIX=/home/prikhi/.nix-profile
fi


# font-cache
xset +fp /usr/share/fonts/local
xset +fp /home/prikhi/.fonts
xset fp rehash

# Nvidia pixmap performance increase (see arch wiki: nvidia)
nvidia-settings -a InitialPixmapPlacement=2

# Start mpdscribble (mpd -> lastfm)
pidof mpdscribble >& /dev/null
if [ $? -ne 0 ]; then
 mpdscribble &
fi

# rotate bckgd
~/.bin/feh-bg &

wmname LG3D &
gpg-agent --daemon &


#dbus-launch awesome
