#!/bin/sh
# X Server Initialization

# Source system config
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi


# Xresources for urxvt
[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources


export SDL_AUDIODRIVER=pulse


# NixOS Specifics
if [ -e /etc/NIXOS ];
then
    export GTK_DATA_PREFIX=/home/prikhi/.nix-profile
fi


# Use ibus as the input method framework
export GTK_IM_MODULE=xim
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon --xim -dr


# font-cache
xset +fp /home/prikhi/.fonts
xset fp rehash

xsetroot -cursor_name left_ptr


# rotate background
~/.bin/feh-bg &


# export the DBUS session's environmental variables
export $(dbus-launch)
