#!/bin/sh
# X Server Initialization

# Source system config
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi


# Xresources for urxvt
[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources


export SDL_AUDIODRIVER=pulse


# NixOS Specifics
if [ -e /etc/NIXOS ];
then
    export GTK_DATA_PREFIX=/home/prikhi/.nix-profile
fi


# Use ibus as the input method framework
export GTK_IM_MODULE=xim
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon --xim -dr


# font-cache
xset +fp /home/prikhi/.fonts
xset fp rehash

xsetroot -cursor_name left_ptr


# rotate background
~/.bin/feh-bg &

# enable mangohud in games
export MANGOHUD=1
# enable raytracing in games
export VKD3D_CONFIG=dxr VKD3D_FEATURE_LEVEL=12_2
# don't mask the nvidia gfx card in proton games
export PROTON_ENABLE_NVAPI=1 PROTON_HIDE_NVIDIA_GPU=0 PROTON_ENABLE_NGX_UPDATER=1

# export the DBUS session's environmental variables
export $(dbus-launch)
