#!/usr/bin/env bash

YOUCOMPLETEME="~/.vim/bundle/youcompleteme"
rm -f "$YOUCOMPLETEME/python/*.so"

mkdir -p ~/ycm_build
cd ~/ycm_build

cmake -G "Unix Makefiles" -DUSE_SYSTEM_LIBCLANG=ON . "$YOUCOMPLETEME/cpp"
make ycm_support_libs
rm -rf ~/ycm_build
