#!/bin/sh

export WINEDEBUG=-all # debug output really screws things with threaded optimisations, so turn them off
export LD_PRELOAD="libpthread.so.0 libGL.so.1"
export __GL_THREADED_OPTIMISATIONS=1
playonlinux --run "Guild Wars 2" &
