#!/usr/bin/env sh
ZK_PATH="${HOME}/z"

cd "${ZK_PATH}" || exit 1

git pull

CHANGES_EXIST="$(git status --porcelain | wc -l)"

if [ "${CHANGES_EXIST}" -eq 0 ]; then
    exit 0
fi

git pull
git add .
git commit -q -m"Last Sync: $(date -Iseconds)"
git push -q
